name: Check Benefits
on:
  schedule:
    - cron : '0 */4 * * *'

jobs:
  build:
    name: get
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
      - name: Run script
        run: |
          pipenv run python get_benefits_sbi.py
      - name: Commit data
        run: |
          git config --local user.email "kanta208@gmail.com"
          git config --local user.name "otomarukanta"
          git commit -m "Update Data" -a
          git push